# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cameraapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cameraapp

  target 'cameraapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cameraappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'cameraapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cameraapp-tvOS

  target 'cameraapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
